### PR TITLE
Bumps this branch to latest upstream master and changed linkage to system freetype.

### PR DESCRIPTION
**Pull request by SlawekNowy**

### CODE REVIEW

**Comment by Silverlan** [comment]
Does this contain any changes that haven't been merged into master yet?

**Comment by SlawekNowy** [comment]
no.

**Comment by Silverlan** [comment]
Are you sure the package names are correct? They fail to install on the runner:
```
E: Unable to locate package libfreetype-devapt-get
E: Unable to locate package install
```

**Comment by SlawekNowy** [comment]
Should be fixed.

**Pull request merged**
