### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by SlawekNowy**

### CODE REVIEW

**Comment by Silverlan** [comment]
Hm... What was the reason for removing freetype from the dependency list? I think it was building correctly before this change, but now it doesn't.
Did something not work with freetype in the dependency list?

**Comment by SlawekNowy** [comment]
It did. In my system (recently switched to EndeavorOS) cmake complained that freetype "dependency" did not exist. Search on google did not yield any meaningful results. Remomal of freetype dep from list worked. I am not sure what's going on right now. Speaking of which, did you even test the binary it produced?

**Comment by Silverlan** [comment]
> It did. In my system (recently switched to EndeavorOS) cmake complained that freetype "dependency" did not exist. Search on google did not yield any meaningful results. Remomal of freetype dep from list worked. I am not sure what's going on right now. Speaking of which, did you even test the binary it produced?
Nah, unfortunately I can't put any time into the Linux build at the moment, so I've only tested the Windows version.
I'd set up some automated tests with GitHub workflows, but the GitHub runners don't have GPU rendering. I might set up a CPU renderer in the future, probably won't be able to get around to that any time soon though.



> Beacuse in my system there are at least few bugs present.
> 
>     1. A missing symbol. For some reason clang never thought of instantiating "prosper::ShaderGraphics::GetRenderPass<prosper::ShaderBlurBase>" despilte it being called at tleast three times in client. (fixed in my working dir)
> 
>     2. lot of dropdowns appear empty, despite the fact that it dedected my install of tf2 It also affect audio system dropdown.
> 
>     3. When I imported 2fort into pragma, a lot of checkerboards and X-es appear.
>        Currently investigating why.

Can you try launching pragma with `-log 2 2 -verbose` and upload the `log.txt` after exiting pragma?

**Comment by Silverlan** [comment]
Speaking of, did you happen to try any of the PFM tutorials? I'm curious if they work at all on Linux.

**Comment by SlawekNowy** [comment]
> Can you try launching pragma with `-log 2 2 -verbose` and upload the `log.txt` after exiting pragma?
Here ya go.
[log.txt](https://github.com/Silverlan/pragma/files/12311787/log.txt)

**Comment by Silverlan** [comment]
> > Can you try launching pragma with `-log 2 2 -verbose` and upload the `log.txt` after exiting pragma?
> > Here ya go.
> > [log.txt](https://github.com/Silverlan/pragma/files/12311787/log.txt)

Thanks! Unfortunately nothing interesting in the log, other than that it can't find the models.
Can you do a pull request for your changes to fix the `ShaderGraphics::GetRenderPass` issue? I can't test it on my Linux system otherwise.

**Comment by SlawekNowy** [comment]
> Speaking of, did you happen to try any of the PFM tutorials? I'm curious if they work at all on Linux.

I ran the intro tutorial, there's no audio button. The file IS logged into console, but it is not loaded.
Missing codec maybe?

**Comment by Silverlan** [comment]
> > Speaking of, did you happen to try any of the PFM tutorials? I'm curious if they work at all on Linux.
> 
> I ran the intro tutorial, there's no audio button. The filepath IS logged into console, but it is not loaded. Missing codec maybe?
> 
> EDIT: Likely, as audio is not muted.

If the audio button is missing altogether, it means it couldn't find the audio asset file. What's your system language? The tutorial audio is only available for the english version right now, for other versions you get english text (because the tutorials aren't translated yet), but no audio, and the audio button would be missing in that case.

I'll try to look into it tomorrow if the build is successful.

**Comment by SlawekNowy** [comment]
My language is polish. In theory I would add envvar LANG to force language for particular session or app. Lemme try thay/

**Comment by SlawekNowy** [comment]
```[locale] [warning] Failed to load localization file 'pfm_core_tutorials.txt' for language 'c': Failed``

https://www.ibm.com/docs/en/aix/7.1?topic=locale-c-posix

**Comment by SlawekNowy** [comment]
https://github.com/Silverlan/sharedutils/blob/7bf50fba1e73ed90a6240ea28bedbcb065c5fdea/src/util.cpp#L984C5-L984C5

Why that line is there if we wanna get the language?

**Comment by SlawekNowy** [comment]
Hmmmm....

```[warning] Unable to precache sound 'pfm\tutorials\intro\welcome.mp3': Invalid format!```

Might be related to third bug i reported.

**Comment by SlawekNowy** [comment]
really?!
```[warning] An error occured trying to load the 'pr_chromium' module: /usr/lib/libpango-1.0.so.0: undefined symbol: hb_ot_color_has_paint
```

**Comment by Silverlan** [comment]
> My language is polish. In theory I would add envvar LANG to force language for particular session or app. Lemme try thay/

Nah, that should be fine. There is no polish translation right now, so it would just default to English, there was another problem though.

Just pushed some changes:
- Should now build properly again on Linux
- Fixed util::get_system_language returning a wrong result

Don't know what's up with the audio yet, I think there's two different problems with it.

**Comment by SlawekNowy** [comment]
Found the problem. The vo files are encoded as mp3's, which are not supported by util_sound at all.

**Comment by SlawekNowy** [comment]
Miniaudio does support wav and mp3, however they are both disabled. Those might be trivial to enable

**Comment by Silverlan** [comment]
> Also the pfm_tutorials tries to mount "vo_pl" directory without a fallback. Whoops?

That is intentional. I plan on translating the tutorials to other languages, but I can't do audio for all of them, and it would be weird if the text was, e.g. in Japanese, but the audio in English, so there is no audio fallback.



> 2\. It's LGPL, and we effectively link it statically to MPL licensed code. (On further inspecion util_sound itself is LGPL, which is fine in shared library context).

`util_sound` is only a utility library for determining the duration of a sound file, it's not used for the actual loading of audio files. I forgot about the license though, I'll do something about that soon.


> Miniaudio does support wav and mp3, however they are both disabled. Those might be trivial to enable

Hm.. there may have been a reason why I didn't enable it, but I don't remember. Thanks for looking into it though! I don't have time this week, but I may be able to give that a shot on the weekend.

**Comment by SlawekNowy** [comment]
I read this out even further. Soloud does all mp3 parsing; what is passed to miniaudio backend is raw data. So soloud devs were right , about disabling mp3 support.
 The problem stems from the fact that it tries to calc the duration in PrecacheSound, but the needed logic is absent on linux systems. Is the precaching needed for mp3s?

**Comment by Silverlan** [comment]
> I read this out even further. Soloud does all mp3 parsing; what is passed to miniaudio backend is raw data. So soloud devs were right , about disabling mp3 support. The problem stems from the fact that it tries to calc the duration in PrecacheSound, but the needed logic is absent on linux systems. Is the precaching needed for mp3s?

It's primarily needed serverside. The server has no actual sound playing capabilities, but still needs to know how long a sound is in certain circumstances.
There is a check for the sound duration clientside as well:
https://github.com/Silverlan/pragma/blob/7fa734b55c56ec2cb328b5103e517c96c6343542/core/client/src/audio/c_sound.cpp#L141

Disabling that check should cause the sound to be played properly, but I'll look for some way to determine mp3 duration on Linux.

**Comment by SlawekNowy** [comment]
I have ported the mpaheader lib for cross-platform compability
https://github.com/SlawekNowy/mpaheader

**Comment by Silverlan** [comment]
> I have ported the mpaheader lib for cross-platform compability https://github.com/SlawekNowy/mpaheader

Thank you! I made some small changes, can you merge my pull request?
https://github.com/SlawekNowy/mpaheader/pull/1

I've already made the changes for it in the rest of the code, just need the merge to activate it.

**Comment by SlawekNowy** [comment]
After making changes to VFilesystem (forgot to merge there?) the sounds now work like a charm.

**Comment by Silverlan** [comment]
> After making changes to VFilesystem (forgot to merge there?) the sounds now work like a charm.

I've merged it now!

**Pull request merged**
